"""empty message

Revision ID: 154c363d63fd
Revises: 53bf23c8b360
Create Date: 2019-12-05 18:54:55.423010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154c363d63fd'
down_revision = '53bf23c8b360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
